name: Build
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0

    - name: Restore packages
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Run unit tests
      run: dotnet test -c Release --no-build -v normal
